GREATLY improved my personal build scripts.

diff --git a/dev/build/build b/dev/build/build
--- a/dev/build/build
+++ b/dev/build/build
@@ -1,9 +1,15 @@
 #!/usr/bin/bash
 
+[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1
+
 source "$(dirname ${0})"/settings
 
-if [ ! -d "${working_dir}" ]; then
-    "${bin_dir}"/refresh
+# Build
+
+# If there's no Makefile, then do a refresh
+if [ ! -f "${BUILD_workarea_path}"/build/Makefile ]; then
+    "$(dirname ${0})"/refresh
 fi
 
-make -C "${working_dir}"/build install
+# make && make install
+make -C "${BUILD_workarea_path}"/build install
diff --git a/dev/build/clean b/dev/build/clean
--- a/dev/build/clean
+++ b/dev/build/clean
@@ -1,7 +1,12 @@
 #!/usr/bin/bash
 
+[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1
+
 source "$(dirname ${0})"/settings
 
-if [ -d "${working_dir}"/build ]; then
-  make -C "${working_dir}"/build clean
+# Clean
+
+if [ -d "${BUILD_workarea_path}"/build ]; then
+    # Delete old build objects
+    make -C "${BUILD_workarea_path}"/build clean
 fi
diff --git a/dev/build/wipe b/dev/build/wipe
--- a/dev/build/wipe
+++ b/dev/build/wipe
@@ -1,17 +1,34 @@
 #!/usr/bin/bash
 
+[ "${EUID}" -eq 0 ] && echo "ERROR: Do not run as root." && exit 1
+
 source "$(dirname ${0})"/settings
 
-\rm -vrf "${working_dir}"
+# Wipe
 
-\rm -vrf "${source_dir}"/autom4te.cache
-\rm -vf "${source_dir}"/Makefile.in
-\rm -vf "${source_dir}"/aclocal.m4
-\rm -vf "${source_dir}"/compile
-\rm -vf "${source_dir}"/config.h
-\rm -vf "${source_dir}"/config.h.in
-\rm -vf "${source_dir}"/config.h.in~
-\rm -vf "${source_dir}"/configure
-\rm -vf "${source_dir}"/depcomp
-\rm -vf "${source_dir}"/install-sh
-\rm -vf "${source_dir}"/missing
+# Check if the working area doesn't even exist
+if [ -d "${BUILD_workarea_path}" ]; then
+
+    # Let GNU Autotools do the cleaning
+    if [ -f "${BUILD_workarea_path}"/build/Makefile ]; then
+        make -C "${BUILD_workarea_path}"/build uninstall
+        make -C "${BUILD_workarea_path}"/build distclean
+    fi
+    
+    # Delete any remaining empty directories
+    find "${BUILD_workarea_path}" -type d -empty -delete
+
+fi
+
+# Delete GNU Autotools poop
+rm -vrf "${BUILD_project_path}"/autom4te.cache
+rm -vf "${BUILD_project_path}"/Makefile.in
+rm -vf "${BUILD_project_path}"/aclocal.m4
+rm -vf "${BUILD_project_path}"/compile
+rm -vf "${BUILD_project_path}"/config.h
+rm -vf "${BUILD_project_path}"/config.h.in
+rm -vf "${BUILD_project_path}"/config.h.in~
+rm -vf "${BUILD_project_path}"/configure
+rm -vf "${BUILD_project_path}"/depcomp
+rm -vf "${BUILD_project_path}"/install-sh
+rm -vf "${BUILD_project_path}"/missing
